# Generated by Django 5.2.7 on 2025-10-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='expected_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
