# Generated by Django 5.2.7 on 2025-10-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_inventoryhistory_expected_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='scanned_at',
            field=models.DateTimeField(null=True),
        ),
    ]
