# Generated by Django 5.2.7 on 2025-10-31 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_optimal_stock_alter_product_min_stock'),
        ('warehouse', '0003_alter_inventoryhistory_scanned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=1)),
                ('row_number', models.IntegerField()),
                ('shelf_number', models.IntegerField(blank=True, null=True)),
                ('last_scan_time', models.DateTimeField()),
                ('last_robot_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['zone', 'row_number'], name='warehouse_z_zone_31e59a_idx'), models.Index(fields=['last_scan_time'], name='warehouse_z_last_sc_db20e9_idx')],
                'unique_together': {('zone', 'row_number')},
            },
        ),
    ]
