# Generated by Django 5.2.7 on 2025-10-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_zonehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoneHistory',
        ),
    ]
