# Generated by Django 5.2.7 on 2025-11-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_optimal_stock_alter_product_min_stock'),
        ('warehouse', '0005_delete_zonehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('days_until_stockout', models.IntegerField()),
                ('recommended_order', models.IntegerField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('current_stock_at_prediction', models.IntegerField(blank=True, null=True)),
                ('avg_daily_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seasonal_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('model_version', models.CharField(default='mock_v1', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prediction', to='products.product')),
            ],
            options={
                'verbose_name': 'AI Прогноз',
                'verbose_name_plural': 'AI Прогнозы',
                'db_table': 'ai_predictions',
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['product', '-prediction_date'], name='ai_predicti_product_5f63b4_idx')],
            },
        ),
    ]
