# Generated by Django 5.2.7 on 2025-11-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_optimal_stock_alter_product_min_stock'),
        ('warehouse', '0006_aiprediction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['is_active', 'days_until_stockout'], name='ai_predicti_is_acti_c5f3ef_idx'),
        ),
    ]
