# Generated by Django 5.2.7 on 2025-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCSVImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('zone', models.CharField(max_length=10)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('shelf_number', models.IntegerField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Импорт CSV',
                'verbose_name_plural': 'Импорты CSV',
            },
        ),
    ]
