# Generated by Django 5.2.7 on 2025-10-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycsvimport',
            name='status',
            field=models.CharField(default='OK', max_length=50),
            preserve_default=False,
        ),
    ]
