# Generated by Django 5.2.7 on 2025-10-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorycsvimport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycsvimport',
            name='status',
        ),
    ]
