# Generated by Django 5.2.7 on 2025-10-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
