# Generated by Django 5.2.7 on 2025-10-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_robot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='secret',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
