# Generated by Django 5.2.7 on 2025-10-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_robot_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='secret',
        ),
    ]
